name: Create Extension Branch

on:
  push:
    branches:
      - main

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub Actions User
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create new Extension Branch
        env:
          TARGET_FOLDER: "extension"
          BRANCH_NAME: "extension"
        run: |
          if [ -d "$TARGET_FOLDER" ]; then
            # Create an orphan branch (fresh start)
            git checkout --orphan "$BRANCH_NAME"

            # Remove all files from the new branch
            git rm -rf .

            # Move contents of the folder to root
            mv $TARGET_FOLDER/* ./

            # Commit and push
            git add .
            git commit -m "Created new branch from $TARGET_FOLDER with unpacked contents"
            git push origin "$BRANCH_NAME"
          else
            echo "Folder $TARGET_FOLDER does not exist. Exiting."
            exit 1
