name: Create New Branch with Custom Name

on:
  push:
    branches:
      - 'main'

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      # Checkout the current code
      - name: Checkout the code
        uses: actions/checkout@v3

      # Set up GitHub Actions User
      - name: Set up Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create Extension Branch
        run: |
          BRANCH_NAME="extension"
          git checkout -b $BRANCH_NAME

      - name: Copy files Extension Folder to Branch
        run: |
          cp -r ./extension/* ./

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Add files from target folder to $BRANCH_NAME"
          git push origin $BRANCH_NAME
