name: Create Extension Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'extension'
        required: true
      source_folder:
        description: 'extension'
        required: true

env:
  TARGET_BRANCH: ${{ github.event.inputs.branch_name }}
  SOURCE_FOLDER: ${{ github.event.inputs.source_folder }}

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create new Extension Branch
        run: |
          git checkout --orphan $TARGET_BRANCH
          git rm -rf .

      - name: Copy files from Extension Folder
        run: |
          mkdir -p temp_copy
          cp -r $SOURCE_FOLDER/* temp_copy/
          mv temp_copy/* .
          rm -rf temp_copy

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Create new branch $TARGET_BRANCH with files from $SOURCE_FOLDER"
          git push origin $TARGET_BRANCH
