name: Release VSIX Package

on:
  push:
    branches:
      - main  # Adjust for the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Choose the node version that works for your repo

      - name: Install dependencies
        run: |
          npm install -g vsce
          npm install

      - name: Set extension name
        id: set_extension_name
        run: |
          echo "EXTENSION_NAME=extension" >> $GITHUB_ENV  # Default name "extension", you can override this in the repository's secrets or elsewhere

      - name: Package VSIX extension
        run: |
          current_date=$(date +'%Y-%m-%d_%H-%M-%S')
          vsce package --out ${{ env.EXTENSION_NAME }}-${current_date}.vsix

      - name: Sign the extension with date
        run: |
          current_date=$(date +'%Y-%m-%d_%H-%M-%S')
          # Assuming OpenSSL is being used to sign the file
          openssl dgst -sha256 -sign myprivatekey.pem -out ${{ env.EXTENSION_NAME }}-${current_date}.vsix.sig ${{ env.EXTENSION_NAME }}-${current_date}.vsix

      - name: Upload VSIX file as artifact
        uses: actions/upload-artifact@v3.2.0
        with:
          name: ${{ env.EXTENSION_NAME }}-vsix
          path: ${{ env.EXTENSION_NAME }}-${current_date}.vsix

      - name: Upload signature as artifact
        uses: actions/upload-artifact@v3.2.0
        with:
          name: ${{ env.EXTENSION_NAME }}-signature
          path: ${{ env.EXTENSION_NAME }}-${current_date}.vsix.sig
