name: Create VSIX Release

on:
  push:
    branches:
      - main 

jobs:
  pack-and-rename:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set current date
      id: date
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create ZIP file
      run: |
        zip -r repository.zip . -x '.git/*' -x '.github/*'

    - name: Rename ZIP to VSIX with prefix and date
      run: |
        PREFIX="shadeview-autobuild"
        NEW_FILENAME="${PREFIX}-${CURRENT_DATE}.vsix"
        mv repository.zip $NEW_FILENAME

    - name: Upload VSIX file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.NEW_FILENAME }}
        path: ${{ env.NEW_FILENAME }}