name: Create VSIX, Release, and Artifact (on Main Push - Manual Version)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true

jobs:
  package-release-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Determine Version
        id: determine-version
        run: |
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT

      - name: Set Prefix (Editable within the script)
        id: set-prefix
        run: |
          # *** EDIT THIS VARIABLE TO CHANGE THE PREFIX ***
          PREFIX="my-custom-extension"
          echo "prefix=$PREFIX" >> $GITHUB_OUTPUT

      - name: Create ZIP archive and Rename
        run: |
          zip -r "${{ steps.set-prefix.outputs.prefix }}-${{ steps.get-date.outputs.date }}.zip" ./* -x "*.git*"
          mv "${{ steps.set-prefix.outputs.prefix }}-${{ steps.get-date.outputs.date }}.zip" "${{ steps.set-prefix.outputs.prefix }}-${{ steps.get-date.outputs.date }}.vsix"
        shell: bash

      - name: Upload VSIX as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-prefix.outputs.prefix }}-${{ steps.get-date.outputs.date }}.vsix
          path: ${{ steps.set-prefix.outputs.prefix }}-${{ steps.get-date.outputs.date }}.vsix
          retention-days: 5

      - name: Configure Git User
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create Tag and Release (Combined)
        run: |
          git tag -a v${{ steps.determine-version.outputs.version }} -m "Release v${{ steps.determine-version.outputs.version }}"
          git push origin v${{ steps.determine-version.outputs.version }}

          gh release create v${{ steps.determine-version.outputs.version }} \
            --title "Release v${{ steps.determine-version.outputs.version }}" \
            --notes "Release of version ${{ steps.determine-version.outputs.version }}.\nVSIX package: ${{ steps.set-prefix.outputs.prefix }}-${{ steps.get-date.outputs.date }}.vsix" \
            --draft=false \
            --prerelease=false \
            "${{ steps.set-prefix.outputs.prefix }}-${{ steps.get-date.outputs.date }}.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash