name: Create VSIX Release

on:
  push:
    branches:
      - main

env:
  RELEASE_PREFIX: 'shadeview-2-autobuild'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Create ZIP package
        run: |
          # Create a ZIP file of the whole repository
          zip -r repo-package.zip . 

      - name: Rename ZIP to VSIX
        run: |
          # Rename the ZIP file to a VSIX file
          mv repo-package.zip release.vsix

      - name: Create Release
        uses: ghcr.io/softprops/action-gh-release@v2.2.1
        with:
          files: release.vsix

      - name: Tag the release with the date and prefix
        run: |
          # Get the current date in YYYY-MM-DD format
          DATE=$(date +'%Y-%m-%d')

          # Construct the release tag using the custom prefix and date
          TAG="${RELEASE_PREFIX}-${DATE}"

          # Create a new git tag with the constructed release name
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"
        
      - name: Upload VSIX to GitHub Release
        uses: actions/upload-artifact@v4.6.0
        with:
          name: release-vsix
          path: release.vsix
